### ISSUE TITLE
Wrong statement about C dependency due to LRZ infrastructure

### ISSUE THREAD

**Issue by K-U-B** [dsymhoven/masterarbeit#24]
https://github.com/dsymhoven/masterarbeit/blob/master/texFiles/masterThesis.tex#L101
This line is not entirely correct. It cannot be stated, that the Leibniz-Rechenzentrum (LRZ)
enforces the use of C. LRZ allows C++ code, also python, or even Java and other languages.

The wish for C has definitely  other reasons, residing in PSC, very old CUDA coding style and preferences of LINUX kernel developers...

**Comment by dsymhoven** [comment]
thx for the info! Appreciate it
